version: '3'

services:
  mongo:
    container_name: mi-mongo
    image: mongo
    ports:
      - '27017:27017'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: toor
    volumes:
      - mi-volumen:/data/db

    networks:
      mi-red:
        ipv4_address: 172.24.0.2


  mongo-express:
    container_name: mi-mongo-express
    image: mongo-express
    restart: always
    ports:
      - '8081:8081'

    networks:
      mi-red:
        ipv4_address: 172.24.0.3
    
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: toor
      ME_CONFIG_MONGODB_SERVER: mi-mongo

    
    volumes:
      - mi-volumen:/data/db
    depends_on:
      - mongo


volumes:
  mi-volumen:
    driver: local

networks:
  mi-red:
    ipam:
        config:
        - subnet: 172.24.0.0/16
    driver: bridge


